---
title: "Candidate1072313"
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
editor: visual
---

# Loading and installing packages

```{r}
options(repos = c(CRAN = "https://cloud.r-project.org/"))
install.packages("ggplot2", repos = "https://cran.rstudio.com/")
install.packages("sf", repos = "https://cran.rstudio.com/")
install.packages("rgbif", repos = "https://cran.rstudio.com/")
install.packages("dplyr", repos = "https://cran.rstudio.com/")
install.packages("tidyverse", repos = "https://cran.rstudio.com/")
install.packages("tibble", repos = "https://cran.rstudio.com/")
install.packages("vegan", repos = "https://cran.rstudio.com/")
install.packages("ggvegan", repos = "https://cran.rstudio.com/")
install.packages("spData", repos = "https://cran.rstudio.com/")
install.packages("ggcorrplot", repos = "https://cran.rstudio.com/")
install.packages("Hmisc", repos = "https://cran.rstudio.com/")
install.packages("spdep", repos = "https://cran.rstudio.com/")
install.packages("spatialreg", repos = "https://cran.rstudio.com/")
install.packages("RColorBrewer", repos = "https://cran.rstudio.com/")
install.packages("pheatmap", repos = "https://cran.rstudio.com/")

library(ggplot2)
library(sf)
library(rgbif)
library(dplyr)
library(tidyverse)
library(tibble)
library(vegan)
library(ggvegan)
library(spData)
library(ggcorrplot)
library(Hmisc)
library(spdep)
library(spatialreg)
library(RColorBrewer)
library(pheatmap)
```

# Downloading, installing and loading data

#### 1. Mae Suai

```{r}
#Downloading
maeSuai <- occ_download(
    pred_default(), 
    pred_gte("distanceFromCentroidInMeters","2000"),
    user = "jessie.nancy12",
    pwd = "GBIF123",
    email = "jessie.durso@keble.ox.ac.uk",
    pred("gadm", "THA.11.10_1"),
    pred("hasCoordinate", TRUE),
    pred_in("basisOfRecord", c("HUMAN_OBSERVATION", "MACHINE_OBSERVATION", "OBSERVATION")),
    format = "SIMPLE_CSV"
  )

#Status of the download
occ_download_meta(maeSuai) 

#Unpacking from a download into a zip, and then importing as a dataframe
maeSuai_get <- occ_download_get(maeSuai, overwrite = TRUE) # Adding as a zip
maeSuai_data <- occ_download_import(maeSuai_get) # Adding as a dataframe
View(maeSuai_data)

#Checking for duplicates
duplicated(maeSuai_data) #No duplicates found

#Saving the file to my laptop so that I can use it for QGIS
write.csv(maeSuai_data,"maeSuai.csv", row.names = FALSE)
```

#### 2. Chiang Rai

```{r}
#Downloading
chiangRai <- occ_download(
  pred_default(), 
  pred_gte("distanceFromCentroidInMeters","2000"),
  user = "jessie.nancy12",
  pwd = "GBIF123",
  email = "jessie.durso@keble.ox.ac.uk",
  pred("gadm", "THA.11_1"),
  pred("hasCoordinate", TRUE),
  pred_in("basisOfRecord", c("HUMAN_OBSERVATION", "MACHINE_OBSERVATION", "OBSERVATION")),
  format = "SIMPLE_CSV"
)

#Status of the download
occ_download_meta(chiangRai)

#Unpacking from a download into a zip, and then importing as a dataframe
chiangRai_get <- occ_download_get(chiangRai, overwrite = TRUE) # Adding as a zip
chiangRai_data <- occ_download_import(chiangRai_get) # Adding as a dataframe
View(chiangRai_data)

#Checking for duplicates
duplicated(chiangRai_data) #No duplicates found

#Saving the file to my laptop so that I can use it for QGIS 
write.csv(chiangRai_data,"chiangRai.csv", row.names = FALSE)
```

# Taxonomic: Correlation Matrix

#### GCom

```{r}
#Completeness score
Gcom <- read.csv("Gcom.csv")
View(Gcom)

#Ensuring all columns are numerical
numericalGCom <- Gcom[1:26,2:7] #This removes the 'Average' row and 'Identifier' column
View(numericalGCom)

#Visualising the correlation matrix
corrGCom <- cor(numericalGCom, method= "spearman")
matrixGCom <- ggcorrplot(corrGCom,
           hc.order = TRUE,
           type = "lower",
           lab = TRUE,
           method = "square")
matrixGCom

#Matrix with the correlation values, and p-values
matrixGComRP <- rcorr(as.matrix(numericalGCom),
                    type = "spearman")
matrixGComRP

#Matrix with the correlation values
##r is the spearman's rank correlation value
rGCom <- matrixGComRP$r
rGCom

#Matrix with the p-values
pGCom <- matrixGComRP$P
pGCom

#Convert matrices to long format
rLongGCom <- as.data.frame(as.table(rGCom))
pLongGCom <- as.data.frame(as.table(pGCom))

#Combining these two tables
resultsGCom <- rLongGCom %>%
  rename(var1 = Var1,
         var2 = Var2,
         rho = Freq) %>%
  mutate(p_value = pLongGCom$Freq)
resultsGCom

#Removing duplicates and self-correlations
resultsGCom <- resultsGCom %>%
  filter(var1 != var2) %>%
  rowwise() %>%
  mutate(pair = paste(sort(c(var1, var2)), collapse = "_")) %>%
  distinct(pair, .keep_all = TRUE) %>%
  ungroup()

#Keeping significant results
sigResults <- resultsGCom %>%
  filter(p_value < 0.05)
sigResults
```

#### GInv

```{r}
GInv <- read_csv("GInv.csv")
View(GInv)

#Ensuring all columns are numerical
numericalGInv <- GInv[1:26,2:7] #This removes the 'Average' row and 'Identifier' column
View(numericalGInv)

#Visualising the correlation matrix
corrGInv <- cor(numericalGInv, method= "spearman")
matrixGInv <- ggcorrplot(corrGInv,
           hc.order = TRUE,
           type = "lower",
           lab = TRUE,
           method = "square")
matrixGInv

#Matrix with the correlation values, and p-values
matrixGInvRP <- rcorr(as.matrix(numericalGInv),
                    type = "spearman")
matrixGInvRP

#Matrix with the correlation values
##r is the spearman's rank correlation value
rGInv <- matrixGInvRP$r
rGInv

# p-value matrix
pGInv <- matrixGInvRP$P
pGInv

#Convert matrices to long format
rLongGInv <- as.data.frame(as.table(rGInv))
pLongGInv <- as.data.frame(as.table(pGInv))


#Combine
resultsGInv <- rLongGInv %>%
  rename(var1 = Var1,
         var2 = Var2,
         rho = Freq) %>%
  mutate(p_value = pLongGInv$Freq)
resultsGInv

#Removing duplicates and self-correlations
resultsGInv <- resultsGInv %>%
  filter(var1 != var2) %>%
  rowwise() %>%
  mutate(pair = paste(sort(c(var1, var2)), collapse = "_")) %>%
  distinct(pair, .keep_all = TRUE) %>%
  ungroup()

#Keeping significant results
sigResultsInv <- resultsGInv %>%
  filter(p_value < 0.05)
sigResultsInv
```

# Redundancy Analysis

#### GCom

```{r}
#Installing data
GCom <- read.csv("GComFactors.csv")
View(GCom)

#Converting to numerical values
numericalGCom <- GCom[1:26,2:12] #This removes the 'Average' row and 'Identifier' column
View(numericalGCom)

#Habitat modification behaving unusually, converting it to a numerical value
numericalGCom$habitatModification <-
  as.numeric(as.character(numericalGCom$habitatModification))

#Checking that everything is numeric
numGCom <- numericalGCom[, sapply(numericalGCom, is.numeric)]

#Data must be normalised for a Redundancy Analysis
normalisedGCom <- scale(numGCom)
View(normalisedGCom)

#Converting normalised data to a dataframe
normalisedGCom <- as.data.frame(scale(numGCom))

species <- normalisedGCom[, c("Arachnida", 
                              "Aves",
                              "Insecta",
                              "Liliopsida",
                              "Magnoliopsida",
                              "Squamata")]
factors <- normalisedGCom[, c("roadDensity",
                                 "waterwayDensity",
                                 "paDensity",
                                 "forestCover",
                                 "habitatModification")]

#Scaling the factors data
factorsScaledGCom <- as.data.frame(scale(factors))

#Running the redundancy analysis
rdaGComResults <- rda(species ~ roadDensity +
                         waterwayDensity +
                         paDensity +
                         forestCover +
                         habitatModification,
               data = factorsScaledGCom)
rdaGComResults

#Do the environmental factors explain species composition better than random distribution?
anova(rdaGComResults) #ANOVA
anova(rdaGComResults, by = "axis") #ANOVA by RDA axis
anova(rdaGComResults, by = "term") #ANOVA by species

#Plotting the RDA
plot(rdaGComResults,
     display = c("species", "bp"),
     scaling = 2)
```

#### GInv

```{r}
#Installing the data
GInv <- read.csv("GInvFactors.csv")
View(GInv)

#Converting to numerical values
numericalGInv <- GInv[1:26,2:12] #This removes the 'Average' row and 'Identifier' column
View(numericalGInv)

#Habitat modification behaving unusually, converting it to a numerical value
numericalGInv$habitatModification <-
  as.numeric(as.character(numericalGInv$habitatModification))

#Checking that everything is numeric
numGInv <- numericalGInv[, sapply(numericalGInv, is.numeric)]

#Data must be normalised for a Redundancy Analysis
normalisedGInv <- scale(numGInv)
View(normalisedGInv)

#Converting normalised data to a dataframe
normalisedGInv <- as.data.frame(scale(numGInv))

speciesInv <- normalisedGInv[, c("Arachnida", 
                              "Aves",
                              "Insecta",
                              "Liliopsida",
                              "Magnoliopsida",
                              "Squamata")]
factorsInv <- normalisedGInv[, c("roadDensity",
                                 "waterwayDensity",
                                 "paDensity",
                                 "forestCover",
                                 "habitatModification")]

#Scaling the environmental factors data
factorsInvScaled <- as.data.frame(scale(factorsInv))

#Running the redundancy analysis
rdaGInvResults <- rda(speciesInv ~ roadDensity +
                         waterwayDensity +
                         paDensity +
                         forestCover +
                         habitatModification,
               data = factorsInvScaled)
rdaGInvResults

#Do the environmental factors explain species composition better than random distribution?
anova(rdaGInvResults)
anova(rdaGInvResults, by = "axis") #ANOVA by RDA axis
anova(rdaGInvResults, by = "term") #ANOVA by species

#Plotting the RDA
plot(rdaGInvResults,
     display = c("species", "bp"),
     scaling = 2)
```

# Spatial autoregression

#### GCom

```{r}

#Installing the 10km*10km Mae Suai grids
maeSuai <- st_read("Grid.shp")
maeSuai

#Re-installing the GCom data
GComMS <- read.csv("GComFactors.csv")
View(GComMS)

#Merging the GCom data and the Mae Suai grid, using the identifier column, which has cells labelled as 1-26.
MSGcom <- merge(maeSuai, GComMS, by="identifier")
MSGcom

#Creating a matrix to understand which cells are next to each other. This uses queen contiguity, which defines neighbouring cells as those sharing a common edge or vertex
MSGComNeighbours <- poly2nb(MSGcom, queen=TRUE)
MSGComNeighbours

#Creating a spatial weighting for the cell, depending on its neighbours
MSGComWeights <- nb2listw(MSGComNeighbours, style="W")
MSGComWeights

taxa <- c("Arachnida", "Aves", "Insecta",
          "Liliopsida", "Magnoliopsida", "Squamata")


#Running the spatial autoregression model
sarGCom <- lapply(taxa, function(taxon) {
  formula <- as.formula(
    paste(
      taxon,
      "~ roadDensity +
         waterwayDensity +
         paDensity +
         forestCover +
         habitatModification"))
  lagsarlm(
    formula,
    data = MSGcom,
    listw = MSGComWeights)})

#Pulling out all coefficients for the spatial autocorrelation
names(sarGCom) <- taxa

#Creating a matrix of the spatial autoregression values for each taxonomic class against each environmental factor, including rho, which measures how strongly neighbouring classes affect each other, and the results
#This model removes the effects of spatial clustering, to run a linear regression.
coefMatrix <- sapply(sarGCom, coef)
round(coefMatrix, 3)

coefMatrixGCom <- sapply(sarGCom, function(model) {
  coef(model)[-1]
})
coefMatrixGCom

#Significance, where p < 0.05
pMatrix <- sapply(sarGCom, function(x) {
  summary(x)$Coef[,4]
})

pMatrixGCom <- sapply(sarGCom, function(model) {
  summary(model)$Coef[-1,4]
})
pMatrixGCom

#Rounding p-values to 4 significant figures
round(pMatrix, 4)

#Creating a table of the Moran's I values of the residuals, to understand how well the spatial autoregression model fit
moranResultsGCom <- lapply(sarGCom, function(model) {
  moran.test(
    residuals(model),
    MSGComWeights,
    zero.policy = TRUE
  )})
moranResultsGCom

moranTableGCom <- data.frame(
  Taxon = names(moranResultsGCom),
  Moran_I = sapply(moranResultsGCom, function(x)
    x$estimate[1]),
  p_value = sapply(moranResultsGCom, function(x)
    x$p.value)
)
moranTableGCom

#Creating heatmap
pheatmap(
  coefMatrix,
  color = colorRampPalette(c("blue", "white", "red"))(100),
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  display_numbers = ifelse(
    pMatrix < 0.05,
    "*",
    ""
  ),
  fontsize_number = 16
)

#Rho
##0 is low spatial clustering, 1 is high spatial clustering
modelStatsGCom <- data.frame(
  Taxon = names(sarGCom),
  AIC = sapply(sarGCom, AIC),
  Rho = sapply(sarGCom, function(x)
    x$rho))
modelStatsGCom
```

#### GInv

```{r}
#Re-installing the GInv data
GInvMS <- read.csv("GInvFactors.csv")
View(GInvMS)

#Merging the GCom data and the Mae Suai grid, using the identifier column, which has cells labelled as 1-26.
MSGinv <- merge(maeSuai, GInvMS, by="identifier")
MSGinv

#Creating a matrix to understand which cells are next to each other using the queen contiguity
MSGInvNeighbours <- poly2nb(MSGinv, queen=TRUE)
MSGInvNeighbours

#Creating a spatial weighting for the cell, depending on its neighbours
MSGInvWeights <- nb2listw(MSGInvNeighbours, style="W")
MSGInvWeights

taxa <- c("Arachnida", "Aves", "Insecta",
          "Liliopsida", "Magnoliopsida", "Squamata")

#Running the spatial autoregression model
sarGInv <- lapply(taxa, function(taxon) {
  formula <- as.formula(
    paste(
      taxon,
      "~ roadDensity +
         waterwayDensity +
         paDensity +
         forestCover +
         habitatModification"))
  lagsarlm(
    formula,
    data = MSGinv,
    listw = MSGInvWeights)})

#Pulling out coefficients for the spatial autocorrelation
names(sarGInv) <- taxa

#Creating a matrix of the spatial autoregression values for each taxonomic class against each environmental factor
coefMatrixInv <- sapply(sarGInv, coef)
round(coefMatrixInv, 3)

coefMatrixGInv <- sapply(sarGInv, function(model) {
  coef(model)[-1]
})
coefMatrixGInv

#Significance, where p < 0.05
pMatrixInv <- sapply(sarGInv, function(x) {
  summary(x)$Coef[,4]
})

round(pMatrixInv, 4)

pMatrixGInv <- sapply(sarGInv, function(model) {
  summary(model)$Coef[-1,4]
})
pMatrixInv

#Creating a table of the Moran's I values of the residuals, to understand how well the spatial autoregression model fit
moranResultsGInv <- lapply(sarGInv, function(model) {
  moran.test(
    residuals(model),
    MSGInvWeights,
    zero.policy = TRUE
  )})
moranResultsGInv

moranTableGInv <- data.frame(
  Taxon = names(moranResultsGInv),
  Moran_I = sapply(moranResultsGInv, function(x)
    x$estimate[1]),
  p_value = sapply(moranResultsGInv, function(x)
    x$p.value)
)
moranTableGInv

#Creating heatmap
pheatmap(
  coefMatrixGInv,
  color = colorRampPalette(c("blue", "white", "red"))(100),
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  display_numbers = ifelse(
    pMatrixInv < 0.05,
    "*",
    ""
  ),
  fontsize_number = 16
)

#0 is low spatial clustering, 1 is high spatial clustering
modelStatsGInv <- data.frame(
  Taxon = names(sarGInv),
  AIC = sapply(sarGInv, AIC),
  Rho = sapply(sarGInv, function(x)
    x$rho))
modelStatsGInv
```
